# -*- coding: utf-8 -*-
"""missing_values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vdff7tqyBuEeaUDL5Y3uMUdakadwcceZ
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Titanic-Dataset.csv")

print(df.head())

print(df.shape)

print(df.isnull().sum())

missing_count = df.isnull().sum()

missing_percentage = (missing_count / len(df)) * 100

summary = pd.DataFrame({
    "Missing Values": missing_count,
    "Missing Percentage": missing_percentage
})

print(summary)

missing = df.isnull().sum()

missing = missing[missing > 0]

print(missing)

import pandas as pd

# Load dataset
df = pd.read_csv("Titanic-Dataset.csv")

# Display first 5 rows
print("First 5 rows:")
print(df.head())

# Dataset information
print("\nDataset Shape:")
print(df.shape)

# Missing value count
missing_count = df.isnull().sum()

# Missing percentage
missing_percentage = (missing_count / len(df)) * 100

# Create summary
summary = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": missing_count.values,
    "Missing Percentage": missing_percentage.values
})

# Show summary
print("\nMissing Value Summary:")
print(summary)

# Show only columns containing missing values
print("\nColumns with Missing Values:")
print(summary[summary["Missing Values"] > 0])

summary.to_excel("missing_value_summary.xlsx", index=False)